### ISSUE TITLE
Add support to check spatial data

### ISSUE THREAD

**Issue by karthik** [karthik/testdat#19]
If there are columns named latitude and longitude, we should check to see that impossible values down show up. 

lat goes from 0° to (+/–)90°.
long goes 0° to (+/–)180°.

**Comment by karthik** [comment]
good point @jhollist

**Comment by Ironholds** [comment]
Would also recommend "lat" and "lon(g)" be treated as analogous. I'll try to find the time to patch this weekend.

**Comment by karthik** [comment]
awesome, thank you.

**Comment by Ironholds** [comment]
Wait: that seems to [https://github.com/ropensci/testdat/blob/master/R/test_coords.R](already exist). What am I missing? Nice integration to check names and scan a particular column?

**Comment by karthik** [comment]
Sorry, totally forgot. Thanks for checking. I need to get back to this package and get the first iteration ready for CRAN and make it work with ensurer which has some functionality that we have been trying to implement. Closing (sorry for the duplicate Oliver).

**Comment by Ironholds** [comment]
NP!

**Comment by Ironholds** [comment]
I'll take the opportunity to go through other bugs and see if there's anything outdated/that I can help with, if you're hoping for a release soon :)

**Comment by karthik** [comment]
Let me do a review today and post a few issues. I'll tag you where you can help!

**Comment by Ironholds** [comment]
KK!
