### ISSUE TITLE
test & fix_white_spaces should accept data frames rather than text

### ISSUE THREAD

**Issue by AnyaB** [karthik/testdat#26]
I'll work this out :-)

**Comment by karthik** [comment]
Awesome, thanks @AnyaB! 

To articulate my reason for allowing this to work just on strings, it already easy to `apply` this function over anything object that is a `character`. So it can be used in the lowest level on a single string object, a vector of strings, or a `data.frame` (using `apply`).

``` S
remove_white_spaces <- function (text)
{
    text <- sub("^ +", "", text)
    text <- sub(" +$", "", text)
    text
}


remove_white_spaces("Karthik Ram ")
# works fine.
```

We can also use this on vectors of strings

``` S
set <- c("This ", "  is", " a ", "poorly  ", " formatted  ", "set  ")
sapply(set, remove_white_spaces)
```

``` S
> sapply(set, remove_white_spaces)
       This            is           a      poorly    formatted          set   
      "This"         "is"          "a"     "poorly"  "formatted"        "set" 
```

We can also use it on a `data.frame`

``` S
df <- data.frame(set)
df2 <- data.frame(apply(df, 2, remove_white_spaces))
> df
           set
1        This 
2           is
3           a 
4     poorly  
5  formatted  
6        set  
> df2
        set
1      This
2        is
3         a
4    poorly
5 formatted
6       set
```

So I'd suggest you leave the existing low(ish) level function as is but write a higher level wrapper that works directly on a `data.frame`. Maybe some thing `fix_white_spaces_df` (we can worry about shortening function names later)

This could be something like:
- take an input data.frame
- Get an index of all columns that are character
- do the apply fix on that index alone and return the result

thoughts?

**Comment by AnyaB** [comment]
Well articulated, Karthik. So the wrapper would be included in a test_all function within testdat. And remove_white_spaces should return the text rather than a T/F logical. Got it. I'll work on the wrapper and close this issue.
